// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bttafojgxjgkcjxhuxuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dGFmb2pneGpna2NqeGh1eHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTQzNjYsImV4cCI6MjA2NzQ3MDM2Nn0.vSm7lqbXH_ZAj_Fvim4dFPTn68aIIT5eaL1KW3iPaBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});